eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dbcar
    username: tu_usuario_de_mariadb
    password: tu_contraseña_de_mariadb
  jpa:
    hibernate:
      ddl-auto: update
  application:
    zipkin: http://localhost:9411